version: "3"

services:
  bot:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      DB_HOST: db
    depends_on:
      - db
  db:
    image: mongo
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/data/db
    ports:
      - ${DB_PORT}:27017
