version: "3"

services:
  bot:
    build: .
    volumes:
      - ./logs:/usr/src/bot/logs
    depends_on:
      - db
    env_file: .env
    environment:
      DB_HOST: db
    restart: unless-stopped

  db:
    image: mongo
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ./db:/data/db
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
